M48
; DRILL file {KiCad 9.0.3} date 2025-07-27T15:47:01-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-27T15:47:01-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.438
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C5.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C6.300
%
G90
G05
T2
X46.0Y-53.0
X46.0Y-67.0
X74.0Y-53.0
X74.0Y-67.0
T3
X60.0Y-60.0
T4
X50.0Y-60.0
X70.0Y-60.0
T1
G00X50.25Y-60.0
M15
G01X69.75Y-60.0
M16
G05
M30
